version: '3.8'
services:
  kea-dhcp:
    image: shourai/kea-dhcp
    container_name: kea-dhcp
    environment:
      - TZ=Europe/Brussels
      - GITHUB_CONFIG_REPO=
    volumes:
      - ./kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf
      - ./leases:/tmp/
    network_mode: host
    restart: always
