name: Build and publish docker image

on:
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
          
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/jorre05/docker-dns:latest
          docker push ghcr.io/jorre05/docker-dns:latest
